version: 0.1

phases:
  build:
    commands:
        - npm install
        - npm run build
artifacts:
  files:
        - build/*
        # - build/media/*
        # - build/css/*
        # - build/js/*
        # - build/index.html
