version: 0.1

phases:
  build:
    commands:
        - npm install
        - npm run build
artifacts:
  files:
        - build/asset-manifest.json
        - build/favicon.ico
        - build/index.html
        - build/manifest.json
        - build/service-worker.js
        - build/static/media/*
        - build/static/css/*
        - build/static/js/*
